spring:
  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

chatapp:
  email:
    url: "https://chatapp.evandhardspace.com"
  rate-limit:
    ip:
      apply-limit: true
  web-socket:
    allowed-origin: "https://chatapp.evandhardspace.com"