chatapp:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: false
  web-socket:
    allowed-origin: "http://localhost:8080"

spring:
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.mailgun.org
    username: evandhardspace@sandbox58184ab0c36b4f0db24fae43c4149877.mailgun.org

jwt:
  expiration-minutes: 1000

nginx:
  require-proxy: false

logging:
  level:
    com.evandhardspace.chatapp: DEBUG
